// website/src/components/Header.tsx
import React from 'react';
import { Link } from 'react-router-dom';

export default function Header() {
  return (
    <header className="bg-slate-800/50 backdrop-blur-sm border-b border-slate-700 sticky top-0 z-50">
      <div className="container mx-auto px-4 py-4 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-2">
          <div className="text-2xl font-bold gradient-text">SightEdit</div>
          <span className="text-xs bg-primary-500 text-white px-2 py-1 rounded">v2.0</span>
        </Link>
        <nav className="flex gap-6">
          <Link to="/" className="hover:text-primary-400">Home</Link>
          <Link to="/examples" className="hover:text-primary-400">Examples</Link>
          <Link to="/docs" className="hover:text-primary-400">Docs</Link>
          <a href="https://github.com/sightedit/sightedit" className="hover:text-primary-400">GitHub</a>
        </nav>
      </div>
    </header>
  );
}

// website/src/components/Header.vue
<template>
  <header class="bg-white shadow-sm border-b border-gray-200 sticky top-0 z-50">
    <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center h-16">
        <!-- Logo -->
        <div class="flex items-center">
          <router-link to="/" class="flex items-center space-x-2">
            <div class="w-8 h-8 bg-gradient-to-br from-primary-500 to-primary-700 rounded-lg flex items-center justify-center">
              <span class="text-white font-bold text-sm">S</span>
            </div>
            <span class="text-xl font-bold text-gray-900">SightEdit</span>
          </router-link>
        </div>
        
        <!-- Navigation -->
        <div class="hidden md:flex items-center space-x-8">
          <router-link 
            v-for="link in navLinks" 
            :key="link.path"
            :to="link.path"
            class="nav-link"
            :class="{ 'active': $route.path === link.path }"
          >
            {{ link.name }}
          </router-link>
        </div>
        
        <!-- CTA -->
        <div class="hidden md:flex items-center space-x-4">
          <a 
            href="https://github.com/sightedit/sightedit" 
            target="_blank"
            class="text-gray-600 hover:text-gray-900 transition-colors"
          >
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
            </svg>
          </a>
          <router-link to="/getting-started" class="btn btn-primary">
            Get Started
          </router-link>
        </div>
        
        <!-- Mobile menu button -->
        <div class="md:hidden">
          <button 
            @click="mobileMenuOpen = !mobileMenuOpen"
            class="text-gray-600 hover:text-gray-900 focus:outline-none"
          >
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path v-if="!mobileMenuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
              <path v-else stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </button>
        </div>
      </div>
      
      <!-- Mobile menu -->
      <div v-if="mobileMenuOpen" class="md:hidden py-4 border-t border-gray-200">
        <div class="space-y-2">
          <router-link 
            v-for="link in navLinks" 
            :key="link.path"
            :to="link.path"
            @click="mobileMenuOpen = false"
            class="block py-2 text-gray-600 hover:text-primary-600 transition-colors"
          >
            {{ link.name }}
          </router-link>
        </div>
        <div class="pt-4 mt-4 border-t border-gray-200">
          <router-link 
            to="/getting-started" 
            @click="mobileMenuOpen = false"
            class="btn btn-primary w-full text-center block"
          >
            Get Started
          </router-link>
        </div>
      </div>
    </nav>
  </header>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const mobileMenuOpen = ref(false);

const navLinks = [
  { name: 'Documentation', path: '/docs' },
  { name: 'Examples', path: '/examples' },
  { name: 'Plugins', path: '/plugins' },
  { name: 'API', path: '/api' },
];
</script>
